# Generated by Django 6.0.2 on 2026-03-21 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="start_day",
            field=models.IntegerField(default=1),
        ),
    ]
