# Generated by Django 6.0.2 on 2026-03-21 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0002_habit_start_day"),
    ]

    operations = []
