# Generated by Django 6.0.2 on 2026-04-19 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0003_auto_20260321_1137"),
    ]

    operations = [
        migrations.AddField(
            model_name="dailyentry",
            name="note",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="habit",
            name="is_archived",
            field=models.BooleanField(default=False),
        ),
    ]
